include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########

INCLUDES = $(all_includes)

noinst_LIBRARIES = libsrc.a

libsrc_a_SOURCES = manage_dyn_slave.c sigel_slave.cpp sigel.cpp 

SUBDIRS = SIGEL_CommonGUI SIGEL_Environment SIGEL_GP SIGEL_MasterGUI SIGEL_Program SIGEL_RealInterface SIGEL_Robot SIGEL_RobotIO SIGEL_Simulation SIGEL_SlaveGUI SIGEL_Tools SIGEL_Visualisation MT_Control MT_GUI MT_GPSystem 

EXTRA_DIST = sigel.cpp sigel_slave.cpp manage_dyn_slave.c 

####### kdevelop will overwrite this part!!! (end)############

