####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = MT_FitnessTranier.h MT_GPManager.h MT_Individual.h MT_Instruction.h MT_Interpreter.h MT_Operand.h MT_Population.h MT_Program.h MT_Programline.h MT_Randomizer.h MT_Search.h MT_SelectionMethod.h MT_Statistics.h MT_StatisticsElement.h MT_Tournament.h MT_TournamentManager.h MT_TrainingCase.h MT_Trainingset.h MT_TranslatedIndividual.h 

####### kdevelop will overwrite this part!!! (end)############
