####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = IFunctions.h SIG_Body.h SIG_CommandParameters.h SIG_CylindricalJoint.h SIG_Drive.h SIG_Geometry.h SIG_GeometryIterator.h SIG_GlueJoint.h SIG_Joint.h SIG_JointSensor.h SIG_LanguageParameters.h SIG_Link.h SIG_Material.h SIG_Mirtich.h SIG_Polygon.h SIG_Robot.h SIG_RobotExceptions.h SIG_RotationalJoint.h SIG_Sensor.h SIG_TranslationalJoint.h SIG_WrongKinematicsException.h SIG_ContactSensor.h SIG_PitchRollSensor.h 

####### kdevelop will overwrite this part!!! (end)############
