####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = SIG_AddIndividualsDialog.h SIG_AllIndividualsView.h SIG_EditCommandDialog.h SIG_EditHostDialog.h SIG_EnvironmentView.h SIG_GUIGPExperiment.h SIG_ExperimentItem.h SIG_ExperimentListView.h SIG_ExperimentView.h SIG_GPParameter.h SIG_IndividualList.h SIG_IndividualListItem.h SIG_IndividualView.h SIG_InfoBox.h SIG_LanguageParameters.h SIG_MainWindow.h SIG_RenameDialog.h SIG_RobotView.h SIG_SimulationParameter.h SIG_TextView.h 

####### kdevelop will overwrite this part!!! (end)############

CLEANFILES=SIG_*Base.h
