####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = SIG_EnvironmentRenderer.h SIG_EnvironmentVisualisation.h SIG_FloatingText.h SIG_RenderRecorder.h SIG_Renderer.h SIG_RobotRenderer.h SIG_RobotVisualisation.h SIG_SceneObject.h SIG_SimulationVisualisation.h SIG_ViewSettings.h SIG_VisualSceneObject.h SIG_Visualisation.h 

####### kdevelop will overwrite this part!!! (end)############
