include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_Visualisation.a

INCLUDES = $(all_includes)

libSIGEL_Visualisation_a_SOURCES = SIG_Visualisation.cpp SIG_VisualSceneObject.cpp SIG_ViewSettings.cpp SIG_SimulationVisualisation.cpp SIG_SceneObject.cpp SIG_RobotVisualisation.cpp SIG_RobotRenderer.cpp SIG_Renderer.cpp SIG_RenderRecorder.cpp SIG_FloatingText.cpp SIG_EnvironmentVisualisation.cpp SIG_EnvironmentRenderer.cpp 


EXTRA_DIST = SIG_EnvironmentRenderer.cpp SIG_EnvironmentVisualisation.cpp SIG_FloatingText.cpp SIG_RenderRecorder.cpp SIG_Renderer.cpp SIG_RobotRenderer.cpp SIG_RobotVisualisation.cpp SIG_SceneObject.cpp SIG_SimulationVisualisation.cpp SIG_ViewSettings.cpp SIG_VisualSceneObject.cpp SIG_Visualisation.cpp 

####### kdevelop will overwrite this part!!! (end)############

