####### kdevelop will overwrite this part!!! (begin)##########

INCLUDES = $(all_includes)

noinst_LIBRARIES = libSIGEL_GP.a

libSIGEL_GP_a_SOURCES = 


EXTRA_DIST = SIG_GPActivePVMHost.h SIG_GPCrossOverTournament.h SIG_GPException.h SIG_GPExperiment.h SIG_GPExperimentHistoryEntry.h SIG_GPFitnessFunction.h SIG_GPFitnessTrainer.h SIG_GPFullDataRecorder.h SIG_GPIndividual.h SIG_GPManager.h SIG_GPMutationTournament.h SIG_GPNiceWalkingFitnessFunction.h SIG_GPOperations.h SIG_GPPVMData.h SIG_GPPVMHost.h SIG_GPPVMTask.h SIG_GPParameter.h SIG_GPPopulation.h SIG_GPRealSpeedFitnessFunction.h SIG_GPSimpleFitnessFunction.h SIG_GPSimpleRecorder.h SIG_GPSimpleTournament.h SIG_GPTournament.h SIG_GPTournamentIndividual.h SIG_GUIGPManager.h SIG_GPAdaptiveWalkingFitnessFunction.h SIG_GPStepperFitnessFunction.h SIG_GPRemoteZORCFitnessFunction.h SIG_GPForceFitnessFunction.h 

####### kdevelop will overwrite this part!!! (end)############
