#!/bin/sh
#
# This script makes the host running it a dynamic client of a
# SIGEL master program started with 'sigel -de':
#
#    sigelDynClient <MasterHostName>
#
# The master starts sigel_slave from /tmp/_SIGEL_EVOLUTION_TEMP on
# this host. The script puts a copy of the SIGEL folder there and
# deletes it when the master releases its dynamic clients.

# The SIGEL folder: run the script there, or modify the next line.
SIGEL_ROOT=$PWD

cd /tmp
rm -rf /tmp/_SIGEL_EVOLUTION_TEMP
cp -R "$SIGEL_ROOT" /tmp/_SIGEL_EVOLUTION_TEMP

# Registers this host with the master and returns when the master releases it.
"$SIGEL_ROOT/manage_dyn_slave" "$1"

cd "$SIGEL_ROOT"
rm -rf /tmp/_SIGEL_EVOLUTION_TEMP

