#!/bin/sh

# Just modify the next line.
SIGEL_ROOT=$PWD

# Don't change the following lines.
export SIGEL_ROOT
PVM_ROOT=$SIGEL_ROOT/supportingLibs/pvm3
PVM_ARCH=LINUX64
export PVM_ROOT PVM_ARCH

# An experiment's slave directory of "." means PVM's own search path.
mkdir -p "$PVM_ROOT/bin/$PVM_ARCH"
ln -sf "$SIGEL_ROOT/sigel_slave" "$PVM_ROOT/bin/$PVM_ARCH/sigel_slave"

PATH=$PVM_ROOT/bin/$PVM_ARCH:$PVM_ROOT/lib:$PATH
export PATH
cd "$SIGEL_ROOT" || exit 1
./sigel "$@"
