include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_RobotIO.a

INCLUDES = $(all_includes)

libSIGEL_RobotIO_a_SOURCES = SIG_UnstreamerScanner.cpp SIG_Scanner.cpp SIG_RobotUnstreamer.cpp SIG_RobotScanner.cpp SIG_RobotIOExceptions.cpp SIG_RobotFactory.cpp SIG_RobotCompilerStructure.cpp SIG_RobotCompilerObjects.cpp SIG_RobotCompiler.cpp SIG_RobotBuilder.cpp 


EXTRA_DIST = SIG_RobotBuilder.cpp SIG_RobotCompiler.cpp SIG_RobotCompilerObjects.cpp SIG_RobotCompilerStructure.cpp SIG_RobotFactory.cpp SIG_RobotIOExceptions.cpp SIG_RobotScanner.cpp SIG_RobotUnstreamer.cpp SIG_Scanner.cpp SIG_UnstreamerScanner.cpp 

####### kdevelop will overwrite this part!!! (end)############

