include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_Program.a

INCLUDES = $(all_includes)

libSIGEL_Program_a_SOURCES = SIG_ProgramLine.cpp SIG_Program.cpp 


EXTRA_DIST = SIG_Program.cpp SIG_ProgramLine.cpp 

####### kdevelop will overwrite this part!!! (end)############
