####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = addIndividualsLarge.xpm addIndividualsSmall.xpm allow.xpm altLogo.png balloonLarge.xpm balloonSmall.xpm deleteExperimentLarge.xpm deleteExperimentSmall.xpm deleteIndividualsLarge.xpm deleteIndividualsSmall.xpm disallow.xpm dnaLarge.xpm dnaSmall.xpm environLarge.xpm environSmall.xpm experimentLarge.xpm experimentSmall.xpm ffButton.xpm individualLarge.xpm individualSmall.xpm newExperimentLarge.xpm newExperimentSmall.xpm noExperiment.png openExperimentLarge.xpm openExperimentSmall.xpm pauseButton.xpm quitApplicationLarge.xpm quitApplicationSmall.xpm robotLarge.xpm robotSmall.xpm saveExperimentLarge.xpm saveExperimentSmall.xpm simulationParameterLarge.xpm simulationParameterSmall.xpm startButton.xpm stepButton.xpm stopButton.xpm videoallow.xpm videodisallow.xpm visualizeLarge.xpm visualizeSmall.xpm 

####### kdevelop will overwrite this part!!! (end)############
