####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = MT_AddConstantsWidget.h MT_Editor.h MT_EstimationWidget.h MT_ExperimentWidget.h MT_IndividualWidget.h MT_MainWindow.h MT_PopulationWidget.h MT_SearchWidget.h MT_SelectionWidget.h MT_StatisticsWidget.h DoubleSpinBox.h MT_ExperimentItem.h MT_PopListViewItem.h MT_WidgetBase.h 

####### kdevelop will overwrite this part!!! (end)############

#CLEANFILES=MT_*Base.h
