include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########

INCLUDES = $(all_includes)

noinst_LIBRARIES = libSIGEL_GP.a

libSIGEL_GP_a_SOURCES = SIG_GPForceFitnessFunction.cpp SIG_GUIGPManager.cpp SIG_GPZorcWalkingFitnessFunction.cpp SIG_GPRemoteZORCFitnessFunction.cpp SIG_GPStepperFitnessFunction.cpp SIG_GPAdaptiveWalkingFitnessFunction.cpp SIG_GPTournamentIndividual.cpp SIG_GPTournament.cpp SIG_GPSimpleTournament.cpp SIG_GPSimpleRecorder.cpp SIG_GPSimpleFitnessFunction.cpp SIG_GPRealSpeedFitnessFunction.cpp SIG_GPPopulation.cpp SIG_GPParameter.cpp SIG_GPPVMTask.cpp SIG_GPPVMHost.cpp SIG_GPPVMData.cpp SIG_GPOperations.cpp SIG_GPNiceWalkingFitnessFunction.cpp SIG_GPMutationTournament.cpp SIG_GPManager.cpp SIG_GPIndividual.cpp SIG_GPFullDataRecorder.cpp SIG_GPFitnessTrainer.cpp SIG_GPFitnessFunction.cpp SIG_GPExperimentHistoryEntry.cpp SIG_GPExperiment.cpp SIG_GPException.cpp SIG_GPCrossOverTournament.cpp SIG_GPActivePVMHost.cpp 


EXTRA_DIST = SIG_GPActivePVMHost.cpp SIG_GPCrossOverTournament.cpp SIG_GPException.cpp SIG_GPExperiment.cpp SIG_GPExperimentHistoryEntry.cpp SIG_GPFitnessFunction.cpp SIG_GPFitnessTrainer.cpp SIG_GPFullDataRecorder.cpp SIG_GPIndividual.cpp SIG_GPManager.cpp SIG_GPMutationTournament.cpp SIG_GPNiceWalkingFitnessFunction.cpp SIG_GPOperations.cpp SIG_GPPVMData.cpp SIG_GPPVMHost.cpp SIG_GPPVMTask.cpp SIG_GPParameter.cpp SIG_GPPopulation.cpp SIG_GPRealSpeedFitnessFunction.cpp SIG_GPSimpleFitnessFunction.cpp SIG_GPSimpleRecorder.cpp SIG_GPSimpleTournament.cpp SIG_GPTournament.cpp SIG_GPTournamentIndividual.cpp SIG_GPAdaptiveWalkingFitnessFunction.cpp SIG_GPStepperFitnessFunction.cpp SIG_GPRemoteZORCFitnessFunction.cpp SIG_GPZorcWalkingFitnessFunction.cpp SIG_GUIGPManager.cpp SIG_GPForceFitnessFunction.cpp 

####### kdevelop will overwrite this part!!! (end)############
