include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_Robot.a

INCLUDES = $(all_includes)

libSIGEL_Robot_a_SOURCES = SIG_PitchRollSensor.cpp SIG_ContactSensor.cpp SIG_WrongKinematicsException.cpp SIG_TranslationalJoint.cpp SIG_Sensor.cpp SIG_RotationalJoint.cpp SIG_Robot.cpp SIG_Polygon.cpp SIG_Mirtich.cpp SIG_Material.cpp SIG_Link.cpp SIG_LanguageParameters.cpp SIG_JointSensor.cpp SIG_Joint.cpp SIG_GlueJoint.cpp SIG_GeometryIterator.cpp SIG_Geometry.cpp SIG_Drive.cpp SIG_CylindricalJoint.cpp SIG_CommandParameters.cpp SIG_Body.cpp IFunctions.cpp 


EXTRA_DIST = IFunctions.cpp SIG_Body.cpp SIG_CommandParameters.cpp SIG_CylindricalJoint.cpp SIG_Drive.cpp SIG_Geometry.cpp SIG_GeometryIterator.cpp SIG_GlueJoint.cpp SIG_Joint.cpp SIG_JointSensor.cpp SIG_LanguageParameters.cpp SIG_Link.cpp SIG_Material.cpp SIG_Mirtich.cpp SIG_Polygon.cpp SIG_Robot.cpp SIG_RotationalJoint.cpp SIG_Sensor.cpp SIG_TranslationalJoint.cpp SIG_WrongKinematicsException.cpp SIG_ContactSensor.cpp SIG_PitchRollSensor.cpp 

####### kdevelop will overwrite this part!!! (end)############
