include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_RealInterface.a

INCLUDES = $(all_includes)

libSIGEL_RealInterface_a_SOURCES = SIG_RealInterface.cpp 


EXTRA_DIST = SIG_RealInterface.cpp 

####### kdevelop will overwrite this part!!! (end)############
