include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_Environment.a

INCLUDES = $(all_includes)

libSIGEL_Environment_a_SOURCES = SIG_Environment.cpp 


EXTRA_DIST = SIG_Environment.cpp 

####### kdevelop will overwrite this part!!! (end)############
