####### kdevelop will overwrite this part!!! (begin)##########

SUBDIRS = kdesigel 

EXTRA_DIST = kdesigel.kdevprj AUTHORS COPYING ChangeLog INSTALL README TODO makefile-rules Makefile.am configure.in dummy.cpp kdesigel.doxygen Makefile 

####### kdevelop will overwrite this part!!! (end)############


