#! /bin/bash

if [ -e /tmp/kdesigelBinary.tar.gz ]
then
 echo 'Deleting kdesigelBinary.tar.gz'
 rm /tmp/kdesigelBinary.tar.gz
fi

if [ -d /tmp/kdesigel ]
then
 echo 'Folder /tmp/kdesigel already exists! Exiting!'
 exit 1
fi

mkdir /tmp/kdesigel /tmp/kdesigel/supportingLibs /tmp/kdesigel/supportingLibs/pvm3 /tmp/kdesigel/supportingLibs/pvm3/bin /tmp/kdesigel/supportingLibs/pvm3/lib /tmp/kdesigel/documentation

cp -R kdesigel/pixmaps /tmp/kdesigel
cp -R kdesigel/supportingLibs/pvm3/bin/LINUX /tmp/kdesigel/supportingLibs/pvm3/bin
cp -R kdesigel/supportingLibs/pvm3/lib/* /tmp/kdesigel/supportingLibs/pvm3/lib/
cp kdesigel/povrayLauncher kdesigel/sigelLauncher kdesigel/sigelDynClient kdesigel/sigel kdesigel/sigel_slave kdesigel/manage_dyn_slave kdesigel/Terrain.ter /tmp/kdesigel

cp kdesigel/supportingLibs/fparser/fparser.txt /tmp/kdesigel/documentation
cp kdesigel/supportingLibs/pvm3/Readme /tmp/kdesigel/supportingLibs/pvm3/
cp COPYING README /tmp/kdesigel

cd /tmp
tar -czf kdesigelBinary.tar.gz kdesigel/
rm -r /tmp/kdesigel/


