####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = LEERE_DATEI SIG_RobotBuilder.h SIG_RobotCompiler.h SIG_RobotCompilerObjects.h SIG_RobotCompilerStructure.h SIG_RobotFactory.h SIG_RobotIOExceptions.h SIG_RobotScanner.h SIG_RobotUnstreamer.h SIG_Scanner.h SIG_UnstreamerScanner.h 

####### kdevelop will overwrite this part!!! (end)############
