####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = SIG_CommandInterface.h SIG_Dyna.h SIG_DynaCallbacks.h SIG_DynaDrive.h SIG_DynaJoint.h SIG_DynaLink.h SIG_DynaMechsCommandInterface.h SIG_DynaMechsLink.h SIG_DynaMechsSimulationData.h SIG_DynaMechsSimulationQueries.h SIG_DynaMoCommandInterface.h SIG_DynaMoSimulationData.h SIG_DynaMoSimulationQueries.h SIG_DynaSensor.h SIG_DynaSystem.h SIG_DynaSystemWrongNumberException.h SIG_Interpreter.h SIG_Recorder.h SIG_RecorderBadRecordingOrderException.h SIG_RecorderNoQueriesSetException.h SIG_Register.h SIG_RegisterWrongSizeException.h SIG_RotationalController.h SIG_Simulation.h SIG_SimulationCannotSolveException.h SIG_SimulationData.h SIG_SimulationParameters.h SIG_SimulationQueries.h SIG_TranslationalController.h SIG_EarlyRunTermSimulation.h 

####### kdevelop will overwrite this part!!! (end)############
