/*
  Copyright 2001 Christian Aue, Abdeladim Benkacem, Jens Busch,
                 Michael Gregorius, Andree Ross, Abdallah Salah Raiyan,
                 Daniel Sawitzki, Volker Strunk, Holger Tuerk,
                 Mihai-Christian Varcol, Jens Ziegler

  This file is part of Sigel.

  Sigel is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Sigel is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Sigel; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
#ifndef SIGEL_ROBOTIO_SIG_ROBOTEXCEPTIONS_H
#define SIGEL_ROBOTIO_SIG_ROBOTEXCEPTIONS_H

#include <qstring.h>
#include "SIGEL_Tools/SIG_Exception.h"

using SIGEL_Tools::SIG_Exception;

namespace SIGEL_RobotIO {
        /**
         * SIG_FileNotFoundError will be thrown if a file that
         * contains urgently needed information could for some
         * reason not be opened. This does not mean that the file
         * does not exist, e.g. one could lack read permission.
         */
        class SIG_FileNotFoundError : public SIG_Exception {
        public:
                /**
                 * Constructor.
                 *
                 * @param file    As in SIG_Exception.
                 * @param line    As in SIG_Exception.
                 * @param unfound This should be the name of the file
                 *                that could not be read.
                 */
                SIG_FileNotFoundError (QString file,
                                       int line,
                                       QString unfound);
        };

        /**
         * This exception will be thrown if the configuration file
         * is not valid. The user should be able to read the message.
         */
        class SIG_SyntaxError : public SIG_Exception {
        public:
                /**
                 * Constructor.
                 *
                 * @param file  As in SIG_Exception.
                 * @param line  As in SIG_Exception.
                 * @param msg   The syntax error will be described in
                 *              stupendous detail here.
                 * @param srcln The line of the source file in which the
                 *              error was detected. This does not mean
                 *              that this is the line in which the error
                 *              actually occurs. Of course the s*** may
                 *              have been written down several paragraphs
                 *              earlier.
                 */
                SIG_SyntaxError (QString file,
                                 int line,
                                 QString msg,
                                 QString filenm,
                                 int srcln);
                static QString int2string (int i);
        };

        /**
         * SIG_SemanticError will be thrown by and only by the
         * compiler, when there are mistakes that make it impossible
         * to correctly build a robot model, but which are not
         * directly related to syntax errors. These may be contradictions,
         * gaps in the description, or even simple
         * typing errors that unintentionally may lead to different
         * identifiers.
         */
        class SIG_SemanticError : public SIG_Exception {
        public:
                /**
                 * Constructor.
                 *
                 * @param file As in SIG_Exception.
                 * @param line As in SIG_Exception.
                 * @param msg  A message describing the error.
                 */
                SIG_SemanticError (QString file,
                                   int line,
                                   QString msg);
        };

        /**
         * In general, streams generated by the program and transfered
         * via network should be readable without any complaint. If,
         * for some weird reason, this not true for a particular stream,
         * this exception will be thrown.
         *
         * This exception will be thrown if a self-generated stream
         * could not be read correctly. These streams are used internally
         * to transmit robot models between components of the distributed
         * system. Be aware that the exception will be thrown by the
         * _receiving_ node. If the user is sitting in front of a machine
         * running the _transmitting_ node (This will generally be true.),
         * he will not notice unless there is a marshalling mechanism in
         * the distribution library.
         */
        class SIG_CorruptedStreamError : public SIG_Exception {
        public:
                /**
                 * Constructor.
                 *
                 * @param file As in SIG_Exception.
                 * @param line As in SIG_Exception.
                 * @param msg  Since there is no real parser reading the
                 *             stream, this is an absolutely senseless and
                 *             useless possibility to incorporate a message
                 *             into the exception. It will normally say
                 *             "Does not work.", or "Help!!!", or
                 *             "Stop that thief!".
		 */
	        SIG_CorruptedStreamError (QString file,
                                          int line,
                                          QString msg);
        };

        /**
         * This exception has nothing to do with reading and parsing
         * a configuration file, but because the facts justifying this
         * exception are detected within the builder, it is now a
         * parser exception. It means: The robot parts not completely
         * connected. In general, a walking robot is ONE tree of
         * open or closed kinematic chains. So starting with any link,
         * one can reach any other link following an alternating chain
         * of joints and links. If this is not true, there will be
         * two robots, or a robot and some forgotten link, or a robot
         * and an amputated leg, or a pile of scattered robot parts
         * lying in a puddle of blood, er, oil.
         */
        class SIG_MultipleChainsError : public SIG_Exception {
        public:
                /**
                 * Constructor.
                 *
                 * @param file As in SIG_Exception.
                 * @param line As in SIG_Exception.
                 * @param msg  A message saying "This is not one robot."
                 *             or something. It is a matter of current
                 *             discussion whether we will be able to enclose
                 *             really senseful information into the message.
                 *             It depends on the algorithm.
                 */
                SIG_MultipleChainsError (QString file,
                                         int line,
                                         QString msg);
        };
}

#endif
