include  $(top_srcdir)/makefile-rules

####### kdevelop will overwrite this part!!! (begin)##########
noinst_LIBRARIES = libSIGEL_Tools.a

INCLUDES = $(all_includes)

libSIGEL_Tools_a_SOURCES = SIG_TypeConverter.cpp SIG_Randomizer.cpp SIG_IO.cpp SIG_Exception.cpp 


EXTRA_DIST = SIG_Exception.cpp SIG_IO.cpp SIG_Randomizer.cpp SIG_TypeConverter.cpp 

####### kdevelop will overwrite this part!!! (end)############

