####### kdevelop will overwrite this part!!! (begin)##########


EXTRA_DIST = SIG_MovieSettingsDialog.h SIG_SimulationControls.h SIG_SimulationVisualisationWidget.h SIG_SimulationWidget.h SIG_SimulationWindow.h 

####### kdevelop will overwrite this part!!! (end)############

CLEANFILES=SIG_*Base.h
